apiVersion: v1
kind: Service
metadata:
  name: iglu-repo-service
  labels:
    app: iglu-repo
spec:
  ports:
  - port: 8020
    name: iglu-repo-port
    targetPort: 8020
    protocol: TCP
  selector:
    app: iglu-repo
