kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-volume
  labels:
    name: kafka-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: kafka-volume
    fsType: ext4
