kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      name: kafka-volume
