apiVersion: v1
kind: Service
metadata:
  name: scala-stream-collector-node
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: scala-stream-collector-node
  type: LoadBalancer
