apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: client-port
    targetPort: 2181
    protocol: TCP
  - port: 2888
    name: leader-port
    targetPort: 2888
    protocol: TCP
  - port: 3888
    name: election-port
    targetPort: 3888
    protocol: TCP
  selector:
    app: zookeeper
