kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      name: zookeeper-volume
