kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper-volume
  labels:
    name: zookeeper-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: zookeeper-volume
    fsType: ext4
